### ISSUE TITLE
Landsat TM/MSS Collection 2 - NASA CMR API Authentication

### ISSUE THREAD

**Issue by Holmes2020** [microsoft/PlanetaryComputerExamples#134]
Hi,

I've been having a look at your "Landsat TM/MSS Collection 2" dataset that is currently in preview and have encountered some difficulty in passing authentication details to the NASA CMR API.

Where do I go to generate a token for the NASA CMR API? Can a token be generated for free or are there data partnership constraints?

Thanks,

Ben

**Comment by TomAugspurger** [comment]
Hi Ben,

I've never used the CMR API before, but I think that https://urs.earthdata.nasa.gov/ is the place to start.

We hope to have these datasets in our STAC API before too much longer, but don't have an exact date yet.
