### ISSUE TITLE
query STAC extension support

### ISSUE THREAD

**Issue by mukhery** [microsoft/PlanetaryComputerExamples#14]
Hi,

Would it be possible to add query support to your STAC endpoints?

As your team noted [here](https://github.com/stac-utils/pystac-client/issues/49), the pystac-client is a little slow when instantiating many items. The query extension would enable some pre-filtering (e.g., based on cloud cover) to help reduce the instantiation of unnecessary items.

For example, a search with the query command below:
```python
api = pystac_client.Client.open(
    "https://planetarycomputer-staging.microsoft.com/api/stac/v1/"
)
s2_search = api.search(
    datetime="2017-09-01/2017-09-05",
    limit=500,
    collections=["sentinel-2-l2a"],
    query=['eo:cloud_cover<5']
)
```
Currently fails with the following error:
```bash
APIError: The 'query' STAC API extension is not yet implemented. You may perform queries against collection IDs, geometry (intersects or bbox), and datetime only. Stay tuned!
```

**Comment by TomAugspurger** [comment]
Yes, we plan to support querying on extension attributes. Anything else to do here, or can this be closed?

**Comment by mukhery** [comment]
Thanks!
