### ISSUE TITLE
Where is last_provisional_slice and/or last_permanent_slice stored in the gridMET Zarr file?

### ISSUE THREAD

**Issue by DKnapp87** [microsoft/PlanetaryComputerExamples#146]
I love the example notebooks, but for the gridMet example, notes 3 and 4 mention last_permanent_slice and last_provisional_slice, but where are those values stored in the Zarr?  I've looked through the various attrs, but don't see where that is stored so that a user knows where the provisional or permanent data ends.  Thanks in advance for an answer.

**Comment by TomAugspurger** [comment]
I'm not actually sure what that's referring to. I wonder if it's to a note in the paper? I don't have a copy to check.
