### ISSUE TITLE
Inaccessibility of Aqua Snow Cover Daily Product with id "MYD10A1 "

### ISSUE THREAD

**Issue by aftabhunzai** [microsoft/PlanetaryComputerExamples#168]
Hi, Your example is working fine with Terra product. I tried to access Aqua Snow Cover Daily  product with its id "MYD10A1" but it is not accessible. Are you going to add this product in near future? 
I used your example but it is not working:

```
for datetime in datelist:
    print(f"Fetching {datetime}")
    search = catalog.search(
        collections=["modis-MYD10A1-061"],
        intersects=location,
        datetime=str(datetime),
    )
    item_aq = search.get_all_items()[0]
    items_aq[datetime] = planetary_computer.sign(item_aq)

print(items_aq)
```

**Comment by TomAugspurger** [comment]
Looking at [our catalog](https://planetarycomputer-staging.microsoft.com/dataset/modis-10A1-061) it looks like the STAC collection ID is `modis-10A1-061`. Can you try that?

**Comment by aftabhunzai** [comment]
Thanks, I got it through following code: it is not mentioned in example:
item_terra = search.get_all_items()[1]

**Comment by TomAugspurger** [comment]
Good to know you worked it out. In general, you could use `item.platform` to find which platform the item came from. And you can query for aqua specifically in the STAC API with `.search(..., query={"platform": {"eq": "aqua"}})`.
