### ISSUE TITLE
add reviewnb to this repo

### ISSUE THREAD

**Issue by raybellwaves** [microsoft/PlanetaryComputerExamples#213]
May help with notebook PRs

https://www.reviewnb.com/

**Comment by TomAugspurger** [comment]
I wish we could, but I *think* that requires approving an oauth application on the Microsoft GitHub organization, which I'm not allowed to do :)

**Comment by raybellwaves** [comment]
I'm thinking of a simple GHA which runs git diff using nbdime (https://github.com/jupyter/nbdime/issues/612#issuecomment-1226629514). I'll report back.

**Comment by TomAugspurger** [comment]
Partly fixed by #214.
