### ISSUE TITLE
Lack of actualised module inside indicators.ipynb

### ISSUE THREAD

**Issue by AlvBuoro** [microsoft/PlanetaryComputerExamples#269]
Runnig the example  the first cell in indicators.ipynb produces this error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 9
      6 import xarray as xr
      8 # climate indicators with xclim
----> 9 import xclim.indicators
     11 # optional imports used in this notebook
     12 from dask.diagnostics import ProgressBar

File /srv/conda/envs/notebook/lib/python3.10/site-packages/xclim/__init__.py:4
      1 """Climate indices computation package based on Xarray."""
      2 from importlib.resources import contents, path
----> 4 from xclim.core import units  # noqa
      5 from xclim.core.indicator import build_indicator_module_from_yaml
      6 from xclim.core.locales import load_locale

File /srv/conda/envs/notebook/lib/python3.10/site-packages/xclim/core/units.py:15
     12 from typing import Any, Callable, Optional, Tuple, Union
     14 import pint.converters
---> 15 import pint.unit
     16 import xarray as xr
     17 from boltons.funcutils import wraps

ModuleNotFoundError: No module named 'pint.unit'

**Comment by TomAugspurger** [comment]
See https://github.com/microsoft/PlanetaryComputer/issues/212.

I think that xclim made a release last week, so we should be able to update the container images shortly.
