### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED error

### ISSUE THREAD

**Issue by rsignell-usgs** [microsoft/PlanetaryComputerExamples#270]
I tried running the [CMIP6 ensemble notebook](https://github.com/microsoft/PlanetaryComputerExamples/blob/main/datasets/cil-gdpcir/ensemble.ipynb) locally (not on the hub) at my current organization and got:
```
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain
```
I know I'm supposed to be pointing at a custom .pem file I have in my home dir, but not sure how to specify that in the context of planetary computer notebooks.

In another notebook, I was able to overcome this by adding `verify=false` to the fsspec `client_kwargs`, but I know that (a) that's not a great solution, and (b) not sure how to even do that here.

**Comment by TomAugspurger** [comment]
Do you know which line gave you that error? Was it

```
catalog = pystac_client.Client.open(
    "https://planetarycomputer.microsoft.com/api/stac/v1/",
    modifier=planetary_computer.sign_inplace,
)
```
?

**Comment by rsignell-usgs** [comment]
Doh!  Can't believe I didn't include that.   But yep, you guessed right!

**Comment by rsignell-usgs** [comment]
I tried and this works without error:
``` python
rom pystac_client.stac_api_io import StacApiIO
from pystac_client.client import Client
stac_api_io = StacApiIO()
stac_api_io.session.verify = "/home/la.signell/PA-RootCA-Cert-2023-Pub.pem"
catalog = Client.open("https://planetarycomputer.microsoft.com/api/stac/v1", stac_io=stac_api_io, modifier=planetary_computer.sign_inplace)
```
but when I try the next step:
```
catalog.get_collection("cil-gdpcir-cc0")
``` 
it is busy for a long time (7.5 minutes!) before failing with:
```
MaxRetryError: HTTPSConnectionPool(host='planetarycomputer.microsoft.com', port=443): Max retries exceeded with url: /api/sas/v1/token/rhgeuwest/cil-gdpcir (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)')))
```

**Comment by TomAugspurger** [comment]
Hmm that's unfortunate. That's eventually coming from the call to our SAS API, using the requests session at https://github.com/microsoft/planetary-computer-sdk-for-python/blob/80006b988948d4e1decc0b4f1afd01dd06cb41de/planetary_computer/sas.py#L444-L460.

Unfortunately, that session is created in the function, so you wouldn't have a chance to modify it like your earlier example.

You might be best off emulating what the `planetary-computer` package does by removing the `modifier=planetary_computer.sign`. Something like

```python
from pystac_client.stac_api_io import StacApiIO
from pystac_client.client import Client
import xarray as xr

stac_api_io = StacApiIO()
stac_api_io.session.verify = ""
catalog = Client.open("https://planetarycomputer.microsoft.com/api/stac/v1", stac_io=stac_api_io)

catalog = catalog.get_collection("cil-gdpcir-cc0")

# get the SAS token
# use either /token/collection-name
# or         /token/account-name/container-name
sas_token = stac_api_io.session.get("https://planetarycomputer.microsoft.com/api/sas/v1/token/cil-gdpcir-cc0").json()["token"]

item = next(catalog.get_all_items())

# Update the items to inject the SAS token
for k, v in item.assets.items():
    v.extra_fields["xarray:open_kwargs"]["storage_options"]["sas_token"] = sas_token
    
    
asset = item.assets["pr"]
ds = xr.open_dataset(asset.href, **asset.extra_fields["xarray:open_kwargs"])
ds
```

I suspect that next you'll say that the call to Azure Blob Storage will fail, but let's see :)

**Comment by TomAugspurger** [comment]
Interesting... this is still with the `cil-gdpcir-cc0` asset?

Maybe it's best to just use the `href` object off the asset and be explicit about everything else. So something like


```python

ds = xr.open_dataset(asset.href, engine="zarr", consolidated=True, chunks={}, storage_options={"account_name": "rhgeuwest", "sas_token": sas_token})

```

"accoun_name" here refers to the storage account the data live in. For `https://rhgeuwest.blob.core.windows.net` it's `rhgeuwest`. You can get this off the collection metadata at `msft:storage_account`.

**Comment by rsignell-usgs** [comment]
```
TypeError: ClientSession._request() got an unexpected keyword argument 'account_name'
```

**Comment by rsignell-usgs** [comment]
Sorry to be such a dunce here

**Comment by TomAugspurger** [comment]
Can you print out your `asset.href`? It might be an `https` url.

If so, you could scrap the `storage_options={"account_name": "rhgeuwest", "sas_token": sas_token}`, and instead append the `sas_token` to the url:

```
ds = xr.open_dataset(asset.href + f"?{sas_token}, engine="zarr", consolidated=True, chunks={})
```

That said, I *think* the cil-gdpcir items all use abfs , since fsspec didn't quite handle query parameters on Zarr files like we needed.

**Comment by rsignell-usgs** [comment]
@TomAugspurger , yes, they are `abfs:`: 

And this works, returning data!

``` python
from pystac_client.stac_api_io import StacApiIO
from pystac_client.client import Client
stac_api_io = StacApiIO()
stac_api_io.session.verify = "/home/rsignell/PA-RootCA-Pub.pem"
catalog = Client.open("https://planetarycomputer.microsoft.com/api/stac/v1", stac_io=stac_api_io)

sas_token = stac_api_io.session.get("https://planetarycomputer.microsoft.com/api/sas/v1/token/cil-gdpcir-cc0").json()["token"]

catalog = catalog.get_collection("cil-gdpcir-cc0")

item = next(catalog.get_all_items())

asset = item.assets["pr"]

ds = xr.open_dataset(asset.href, engine="zarr", consolidated=True, chunks={}, 
                     storage_options={"account_name": "rhgeuwest", "sas_token": sas_token})
```

**Comment by rsignell** [comment]
@TomAugspurger, revisiting this issue as I'm working with the NATO folks again on accessing the Sentinel1 data, for which the item assets *do* have hrefs that are `https:` urls.  

So I can open these successfully in xarray by appending the `sas_token` as you suggest:
```
tokenized_href = f"{item.assets['hh'].href}?{sas_token}"
da = xr.open_dataset(tokenized_href, engine='rasterio', chunks={'x':512, 'y':512}).squeeze(drop=True)
```
but of course I *really* want to access the data using `stackstac` or `odc.stac`.    

Do you know how I would pass my `sas_token` to those tools?

**Comment by rsignell** [comment]
Doh!  Okay, makes sense!

**Comment by rsignell** [comment]
I got odc.stac to work using this approach!
https://nbviewer.org/gist/rsignell/c32949c59574beca9262e27dcc1de2eb
Thanks for the help @TomAugspurger !
