### ISSUE TITLE
Xclim example not running

### ISSUE THREAD

**Issue by AlvBuoro** [microsoft/PlanetaryComputerExamples#272]
Hi, the notebook at https://planetarycomputer.microsoft.com/dataset/cil-gdpcir-cc-by#Climate-indicators is not working.
I am aware that Xclim has a new release and it apparently is not adjusted in your sever yet.

**Comment by TomAugspurger** [comment]
Thanks for the report. Follow along at https://github.com/microsoft/PlanetaryComputer/issues/212 for updates.

In the meantime, you might be able to `pip install -U xclim` after you're notebook server starts.
