### ISSUE TITLE
"ConformanceError: API does not conform"

### ISSUE THREAD

**Issue by Holmes2020** [microsoft/PlanetaryComputerExamples#48]
Hi,

I am new to EO data and have started following your 'Cloudless Mosaic' tutorial to familiarise myself with accessing satellite data through the api. I have pip installed the pystac_client, however when I run the following command:

**stac = pystac_client.Client.open("https://planetarycomputer.microsoft.com/api/stac/v1")**

I receive the error:

**ConformanceError: API does not conform to {ConformanceClasses.STAC_API_CORE}. Must contain one of the following URIs to conform (preferably the first):
	https://api.stacspec.org/v1.0.0-beta.1/core
	http://stacspec.org/spec/api/1.0.0-beta.1/core.**

Any help or guidance would be greatly appreciated. Thank you.

Ben

**Comment by TomAugspurger** [comment]
Hi Ben,

Sorry about the disruption. As noted in our [changelog](https://planetarycomputer.microsoft.com/docs/overview/changelog/#apis) our catalog is now STAC 1.0, but the fully-released pystac and pystac-client aren't yet compatible with that. Both those libraries have release candidates available, which you can install with

```
$ pip install --pre --upgrade pystac pystac-client
```

or you can use the docker images we use in our hub (which include those versions)

```
$ docker pull mcr.microsoft.com/planetary-computer/python
```

**Comment by Holmes2020** [comment]
Hi Tom,

Brilliant, that fixed the problem! Really appreciate the quick response.

Best wishes,
Ben
