### ISSUE TITLE
pystac_client ConformanceError

### ISSUE THREAD

**Issue by samsammurphy** [microsoft/PlanetaryComputerExamples#51]
Following [Reading Data from the STAC API](https://github.com/microsoft/PlanetaryComputerExamples/blob/main/quickstarts/reading-stac.ipynb)

I hit a ConformanceError raised by pystac_client. Apparently "must contain one of the following URIs"

-  https://api.stacspec.org/v1.0.0-beta.1/core
-  http://stacspec.org/spec/api/1.0.0-beta.1/core.

```
from pystac_client import Client
catalog = Client.open("https://planetarycomputer.microsoft.com/api/stac/v1")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\smurphy1\Miniconda3\envs\mpc\lib\site-packages\pystac_client\client.py", line 98, in open
    catalog = cls.from_file(url)
  File "C:\Users\smurphy1\Miniconda3\envs\mpc\lib\site-packages\pystac\stac_object.py", line 496, in from_file
    o = cls.from_dict(d, href=href)
  File "C:\Users\smurphy1\Miniconda3\envs\mpc\lib\site-packages\pystac_client\client.py", line 134, in from_dict
    catalog = cls(
  File "C:\Users\smurphy1\Miniconda3\envs\mpc\lib\site-packages\pystac_client\client.py", line 68, in __init__
    raise ConformanceError(
pystac_client.exceptions.ConformanceError: API does not conform to {ConformanceClasses.STAC_API_CORE}. Must contain one
of the following URIs to conform (preferably the first):
        https://api.stacspec.org/v1.0.0-beta.1/core
        http://stacspec.org/spec/api/1.0.0-beta.1/core.
```

Steps to reproduce

- Create a new conda environment in Windows
- pip install planetary-computer
- pip install pystac-client

Versions

```
Python 3.9.6
pystac-client      0.1.1
pystac             0.5.6
planetary-computer 0.2.2
```

**Comment by TomAugspurger** [comment]
Sorry about that, comes from your versions of pystac and pystac-client not supporting pystac 1.0 yet. See https://github.com/microsoft/PlanetaryComputerExamples/issues/48#issuecomment-880602596.

pystac 1.0.0 was just released STAC 1.0 support, and pystac-client should be coming in the next day or two.
