### ISSUE TITLE
Reading Data from the STAC API tutorial - Conformance Error

### ISSUE THREAD

**Issue by pblankenau2** [microsoft/PlanetaryComputerExamples#53]
I was trying to run the tutorial here https://github.com/microsoft/PlanetaryComputerExamples/blob/main/quickstarts/reading-stac.ipynb, and I received the following error message.  I also tried upgrading to the pystac-client v0.2.0b2 version but received the same error.

![image](https://user-images.githubusercontent.com/13680523/126359733-eebaa999-1a72-4105-964c-03a8acf642b8.png)

**Comment by TomAugspurger** [comment]
Sorry about that. This comes from your versions of pystac and pystac-client not supporting STAC 1.0. See #48 (comment).

pystac 1.0.0 was just released with STAC 1.0 support. A pystac-client release with STAC 1.0 support should be coming in the next day or two. In the meantime, you can `pip install --upgrade --pre pystac pystac-client` to get a pre-release version of pystac-client that supports STAC 1.0
