### ISSUE TITLE
GPU environment has corrupted GDAL installation

### ISSUE THREAD

**Issue by k3blu3** [microsoft/PlanetaryComputerExamples#66]
Apologies if this isn't the right place to be posting this issue.

All GDAL dependencies seem to work properly in the CPU environment with the Pangeo Notebook. However, the GDAL/rasterio installations seem to be broken when you spin up a GPU machine on the Hub. If I open a terminal and type in gdalinfo I get this error:

```
gdalinfo: error while loading shared libraries: libdeflate.so.0: cannot open shared object file: no such file or directory
```

**Comment by TomAugspurger** [comment]
Thanks for the report, I've confirmed that I see the issue too.

I'll see if I can diagnose the problem and will get a fixed image built.

**Comment by TomAugspurger** [comment]
@k3blu3 this should be fixed now if you want to try it out again. Thanks again for reporting it.

For reference, the `2021.08.16.0` tag at https://github.com/microsoft/planetary-computer-containers is the fixed version.
