### ISSUE TITLE
Sentinel-2-l2a band 10 availability

### ISSUE THREAD

**Issue by Holmes2020** [microsoft/PlanetaryComputerExamples#68]
Hi,

I have noticed that when checking the available assets for the sentinel-2-l2a dataset that band B10 appears to be absent.
Will this band be accessible through the Planetary Computer api in the future?

Best wishes,
Ben

**Comment by TomAugspurger** [comment]
B10 is excluded from Level 2A on places like Sentinel Hub too. From https://docs.sentinel-hub.com/api/latest/data/sentinel-2-l2a/

> Note: The cirrus band B10 is excluded as it does not contain any "bottom of the atmosphere" information (Source: [Sen2Cor Configuration and User Manual](https://step.esa.int/thirdparties/sen2cor/2.5.5/docs/S2-PDGS-MPC-L2A-SUM-V2.5.5_V2.pdf)).

Do you have a need for it?

**Comment by Holmes2020** [comment]
> B10 is excluded from Level 2A on places like Sentinel Hub too. From https://docs.sentinel-hub.com/api/latest/data/sentinel-2-l2a/
> 
> > Note: The cirrus band B10 is excluded as it does not contain any "bottom of the atmosphere" information (Source: [Sen2Cor Configuration and User Manual](https://step.esa.int/thirdparties/sen2cor/2.5.5/docs/S2-PDGS-MPC-L2A-SUM-V2.5.5_V2.pdf)).
> 
> Do you have a need for it?

Hi Tom,

Thank you for your reply. You are quite right, I've just been looking over the sentinel 2a documentation and it appears that band 10 is intentionally excluded.

My reason for asking is that I had been looking into the s2cloudless classifier for effective cloud masking and it appears that this algorithm requires band 10 as an input.

I can obtain this band information through other APIs though, so it is not too much of a hurdle.

Ben

**Comment by TomAugspurger** [comment]
Thanks. My understanding (but I'm not an expert) is that s2cloudless was trained on Level 1 data, so it might not perform well on Level 2 data, even if band 10 were available.

You might not be surprised to hear that we're also looking into Sentinel cloud masks :) Not ETA yet, but hopefully in the next 3-6 months we'll have something that covers your needs.

**Comment by cordmaur** [comment]
Hi @Holmes2020, while there is no "reliable" Sentinel cloud mask in Planetary Computer, I published a workaround to use S2Cloudless with PC. Here is the link:
https://towardsdatascience.com/creating-sentinel-2-truly-cloudless-mosaics-with-microsoft-planetary-computer-7392a2c0d96c
